### ISSUE TITLE
Better application icon

### ISSUE THREAD

**Issue by ma1onso** [AlonsoEnrique/Quotes#1]
@alphaphee

**Comment by alphaphee** [comment]
@alons45 Sorry for the delayed answer, I 've been quite busy the last few days. I will happily give it a shot.

**Comment by Fercho191** [comment]
Do you have any idea with the logo you want? I can help you at this point

**Comment by ma1onso** [comment]
@Fercho191 I need to improve the current icon https://github.com/AlonsoEnrique/Quotes/tree/master/data/images/icons do not forget the elementary guides: https://elementary.io/docs/human-interface-guidelines#iconography thanks!!!

**Comment by NathanBnm** [comment]
I have an idea for the icon. If you want I can work on this. It will be based with the 🙶 and 🙷 symbols and the letter Q.

**Comment by ma1onso** [comment]
@NathanBnm of course, i have little time these days, your help is very valuable. Thanks

**Comment by NathanBnm** [comment]
Sure! I'm going to see what I can propose you when I have time, probably next week.

**Comment by NathanBnm** [comment]
I'm sorry about that but I haven't so much time finally, and I tried something but it's not very good :confused: I'll see if I can propose you something, but other propositions are still appreciated :smile:

**Comment by ryonakano** [comment]
![Screenshot from 2019-06-09 20-29-20](https://user-images.githubusercontent.com/26003928/59158453-4de53b80-8af5-11e9-9af1-0acf34d18d8c.png)

What do you think about this icon? I just made one as an experiment.

Actually the 🙶 and 🙷 symbols and the letter Q is just brought from the old one, but now they are converted to path. The icon itself is [template](https://github.com/micahilbery/elementary-icon-templates). Also, I added gradations for the icon color or shadows for symbol with the way [elementary HIG encourages](https://elementary.io/docs/human-interface-guidelines#pictogram-shadow). The color of fill of the icon is \#3d211b for bottom and \#715344 for top, which are in [elementary color palette](https://elementary.io/docs/human-interface-guidelines#color).

Please let me know if you would like to use other colors, change the symbol, and so on.

**Comment by NathanBnm** [comment]
Personaly I find it great, but as elementary HIG said we have to avoid icons on a square background. Maybe there is a way to improve this. However this is looking better and simpler than before.

I was thinking too. Maybe the letter "Q" is not so universal, depending on the languages it will change the name of the app.

**Comment by ma1onso** [comment]
@ryonakano I like

**Comment by NathanBnm** [comment]
@Fatih20 any proposition?

**Comment by Fatih20** [comment]
I think the one proposed by @ryonakano still could be improved to comply by the HIG even better. I worry mostly about whether this project is dead or not.

**Comment by ma1onso** [comment]
The project is alive :smile: don't worry

**Comment by Fatih20** [comment]
I'll work on it then.

**Comment by NathanBnm** [comment]
@Fatih20 any update on this?

**Comment by Fatih20** [comment]
@NathanBnm https://github.com/ma1onso/quotes/pull/33
