### ISSUE TITLE
Facebook share isn't working

### ISSUE THREAD

**Issue by NathanBnm** [AlonsoEnrique/Quotes#16]
Here is the error message when clicking on the Facebook share button:

> User is not allowed to see the application.: The user is not allowed to see this application due to the developer settings configuration.

**Comment by NathanBnm** [comment]
What about this, did you find a solution?

**Comment by ma1onso** [comment]
Hi @NathanBnm actually I'm busy with other projects. Sorry :(

**Comment by NathanBnm** [comment]
Okay no problem, don't pay attention at the PR I made for now :wink:  I have to review it

**Comment by ma1onso** [comment]
![image](https://user-images.githubusercontent.com/1877511/71645334-c9caef00-2ca4-11ea-938b-30029dcd1ef6.png)
Fixed
