### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by NathanBnm** [AlonsoEnrique/Quotes#28]
As explained by @ryonakano in #17 you should configure your repository for Travis CI.
Maybe more details to post here.

**Comment by ryonakano** [comment]
Also see https://github.com/elementary/houston/wiki/Continuous-Integration if needed.

**Comment by ma1onso** [comment]
Completed #30

**Comment by ryonakano** [comment]
@ma1onso You also need to log in [Travis CI](https://travis-ci.org/) and enable CI for this repository like this:

![Screenshot from 2020-01-02 10-04-26](https://user-images.githubusercontent.com/26003928/71648482-19162b80-2d48-11ea-99e8-35fdcf281491.png)

**Comment by ma1onso** [comment]
It's already set. Thanks!
![image](https://user-images.githubusercontent.com/1877511/71648561-019d5b00-2cd4-11ea-9d6b-732777a41d02.png)
