### ISSUE TITLE
Entire source in deb packaging branch

### ISSUE THREAD

**Issue by danirabbit** [AlonsoEnrique/Quotes#35]
Since your old source is in the `deb-packaging-loki` branch, the package being built is that old release 0.5.6

You probably want to rename that branch to just `loki` so that your new release gets built in AppCenter

**Comment by ma1onso** [comment]
@danrabbit done : )

**Comment by ma1onso** [comment]
@danrabbit now Travis throw an error 
[log.txt](https://github.com/ma1onso/quotes/files/4109545/log.txt)
