### ISSUE TITLE
Change requested for AppCenter: Name already in use

### ISSUE THREAD

**Issue by cassidyjames** [AlonsoEnrique/Quotes#38]
Thanks for submitting an app to AppCenter. While reviewing your app, we noticed it uses the name of an existing app in AppCenter:

https://appcenter.elementary.io/com.github.alonsoenrique.quotes/

As stated in the [publishing requirements](https://github.com/elementary/houston/wiki/Before-You-Publish#naming):

>To protect both users and developers, your app's name must not be the same as or confusingly similar to an existing app in AppCenter or other brand, as determined by app reviewers.

Please change the name to something unique in at least the following user-facing areas and resubmit a new release:

- [ ] AppData name:
https://github.com/ma1onso/quotes/blob/8cde1e2dc6d903c6e822bcc7e6bc1921bbadc20a/data/com.github.ma1onso.quotes.appdata.xml.in#L7
- [ ] Launcher name:
https://github.com/ma1onso/quotes/blob/8cde1e2dc6d903c6e822bcc7e6bc1921bbadc20a/data/com.github.ma1onso.quotes.desktop.in#L2
- [ ] HeaderBar title:
https://github.com/ma1onso/quotes/blob/6124947ac804fbef0cf9cf1ee5b5856656ade30a/src/Configs/Properties.vala#L30

Note that the code repository, RDNN, and class names **do not** need to change, as they are not user-facing.

**Comment by ma1onso** [comment]
Hi @cassidyjames, https://appcenter.elementary.io/com.github.alonsoenrique.quotes/ is the same app, but I resubmit the again from zero because I renamed my GitHub account from alonsoenrique to ma1onso. Another way of solving this issue?

**Comment by cassidyjames** [comment]
@ma1onso ah, I'm not sure if we have a way to handle that cleanly. Let me look into it!

**Comment by ma1onso** [comment]
> @ma1onso ah, I'm not sure if we have a way to handle that cleanly. Let me look into it!

@cassidyjames Thanks!. I already submitted my application with another name, what I should do? submit the application with the original name when you respond to me?

**Comment by ma1onso** [comment]
@cassidyjames any news?

**Comment by cassidyjames** [comment]
@ma1onso sorry, not yet—but I am seeing if we can use appdata to help migrate people over, or if we'll need to create a manual package or something.

**Comment by ma1onso** [comment]
> @ma1onso sorry, not yet—but I am seeing if we can use appdata to help migrate people over, or if we'll need to create a manual package or something.

Ok :+1:

**Comment by ma1onso** [comment]
@cassidyjames :'(
