### ISSUE TITLE
Brand colors do not pass WCAG AA contrast check

### ISSUE THREAD

**Issue by danirabbit** [AlonsoEnrique/Quotes#7]
https://github.com/AlonsoEnrique/Quotes/blob/830e8d033be6c86906d0a0e85c3227d5565a96d5/data/com.github.alonsoenrique.quotes.appdata.xml#L29

These colors [do not contrast well enough](https://snook.ca/technical/colour_contrast/colour.html#fg=77B7C6,bg=6F8A91) to guarantee legibility. You should try to meet WCAG AA

**Comment by ma1onso** [comment]
I changed to this: https://snook.ca/technical/colour_contrast/colour.html#fg=121212,bg=6F8A91 7c023b25108c81035aede5c3daa8bf9167741aa4
